import { CatalogItem } from './catalog-item.model';

export const CATALOG_ITEMS: readonly CatalogItem[] = [
  {
    id: 'shield-t1',
    name: 'ESCUDO DE APRENDIZ',
    description: 'ABSORBE 1 FALLO PUNTUAL',
    fullDescription: 'Proteccion fundamental de una sola carga. Cubre al alumno de un typo o un error puntual en su primera entrega.',
    type: 'EQUIPMENT',
    family: 'SHIELD',
    tier: 'COMUN',
    price: 200,
    icon: 'shield',
    accent: 'PURPLE',
    imageUrl: 'assets/items/escudo.png',
    imageAlt: 'Escudo de aprendiz',
    status: 'AVAILABLE',
    effect: '1 carga'
  },
  {
    id: 'shield-t2',
    name: 'ESCUDO REFORZADO',
    description: 'ABSORBE 2 FALLOS SUCESIVOS',
    fullDescription: 'Forjado con doble nucleo de absorcion. Permite cometer hasta dos equivocaciones en desafios practicos.',
    type: 'EQUIPMENT',
    family: 'SHIELD',
    tier: 'POCO COMUN',
    price: 500,
    icon: 'shield',
    accent: 'CYAN',
    imageUrl: 'assets/items/escudo.png',
    imageAlt: 'Escudo reforzado',
    status: 'AVAILABLE',
    effect: '2 cargas'
  },
  {
    id: 'shield-t3',
    name: 'ESCUDO BALUARTE TDD',
    description: 'ABSORBE 3 FALLOS CONSECUTIVOS',
    fullDescription: 'Construido para metodologias Test-Driven Development. Soporta hasta 3 fallas sucesivas mientras se itera el codigo verde.',
    type: 'EQUIPMENT',
    family: 'SHIELD',
    tier: 'RARO',
    price: 1000,
    icon: 'shield',
    accent: 'PINK',
    imageUrl: 'assets/items/escudo.png',
    imageAlt: 'Escudo baluarte TDD',
    status: 'AVAILABLE',
    effect: '3 cargas'
  },
  {
    id: 'shield-t4',
    name: 'BALUARTE TITANICO',
    description: 'BARRERA DE 5 CARGAS',
    fullDescription: 'Armadura pesada de 5 nucleos de absorcion para cubrir al estudiante durante un sprint de entregas complejas.',
    type: 'EQUIPMENT',
    family: 'SHIELD',
    tier: 'EPICO',
    price: 2000,
    icon: 'shield',
    accent: 'YELLOW',
    imageUrl: 'assets/items/escudo.png',
    imageAlt: 'Baluarte titanico',
    status: 'AVAILABLE',
    effect: '5 cargas'
  },
  {
    id: 'shield-t5',
    name: 'EGIDA IMPERIAL',
    description: 'BLINDAJE DE 8 CARGAS',
    fullDescription: 'La maxima reliquia defensiva. Absorbe hasta 8 fallos en examenes parciales oficiales o retos boss sin penalizacion de vidas.',
    type: 'EQUIPMENT',
    family: 'SHIELD',
    tier: 'LEGENDARIO',
    price: 4000,
    icon: 'shield',
    accent: 'PURPLE',
    imageUrl: 'assets/items/escudo.png',
    imageAlt: 'Egida imperial',
    status: 'AVAILABLE',
    effect: '8 cargas'
  },
  {
    id: 'xp-boost-t1',
    name: 'TONICO DE CONCENTRACION',
    description: '+25% XP DURANTE 1 HORA',
    fullDescription: 'Brebaje pedagogico ligero que potencia la absorcion de conceptos en sesiones cortas de practica.',
    type: 'BUFF',
    family: 'EXPERIENCE',
    tier: 'COMUN',
    price: 200,
    icon: 'xp',
    accent: 'CYAN',
    imageUrl: 'assets/items/experiencia.png',
    imageAlt: 'Tonico de concentracion',
    status: 'AVAILABLE',
    effect: 'x1.25 XP'
  },
  {
    id: 'xp-boost-t2',
    name: 'ELIXIR DE SABIDURIA',
    description: '+50% XP DURANTE 2 HORAS',
    fullDescription: 'Otorga un impulso sustancial de experiencia para avanzar rapidamente a traves de guias y ejercicios del modulo.',
    type: 'BUFF',
    family: 'EXPERIENCE',
    tier: 'POCO COMUN',
    price: 500,
    icon: 'xp',
    accent: 'PURPLE',
    imageUrl: 'assets/items/experiencia.png',
    imageAlt: 'Elixir de sabiduria',
    status: 'AVAILABLE',
    effect: 'x1.5 XP'
  },
  {
    id: 'xp-boost-t3',
    name: 'ELIXIR DE HIPEREXPERIENCIA',
    description: 'DUPLICA XP POR 4 HORAS',
    fullDescription: 'Pocion de alquimia academica que duplica todos los puntos de experiencia obtenidos. Ideal para sesiones intensivas.',
    type: 'BUFF',
    family: 'EXPERIENCE',
    tier: 'RARO',
    price: 1000,
    icon: 'xp',
    accent: 'PINK',
    imageUrl: 'assets/items/experiencia.png',
    imageAlt: 'Elixir de hiperexperiencia',
    status: 'AVAILABLE',
    effect: 'x2 XP'
  },
  {
    id: 'xp-boost-t4',
    name: 'TOMO DEL DOBLE TITAN',
    description: 'X2.5 XP DURANTE 8 HORAS',
    fullDescription: 'Artefacto de progresion acelerada para ascender en el ranking de la cohorte durante jornadas completas de laboratorio.',
    type: 'BUFF',
    family: 'EXPERIENCE',
    tier: 'EPICO',
    price: 2000,
    icon: 'xp',
    accent: 'YELLOW',
    imageUrl: 'assets/items/experiencia.png',
    imageAlt: 'Tomo del doble titan',
    status: 'AVAILABLE',
    effect: 'x2.5 XP'
  },
  {
    id: 'xp-boost-t5',
    name: 'CORONA DE OMNISCIENCIA',
    description: 'TRIPLICA XP POR 24 HORAS',
    fullDescription: 'La maxima bendicion de conocimiento. Triplica todo el XP cosechado en desafios, quizzes y entregas durante un dia entero.',
    type: 'BUFF',
    family: 'EXPERIENCE',
    tier: 'LEGENDARIO',
    price: 4000,
    icon: 'xp',
    accent: 'CYAN',
    imageUrl: 'assets/items/experiencia.png',
    imageAlt: 'Corona de omnisciencia',
    status: 'AVAILABLE',
    effect: 'x3 XP'
  },
  {
    id: 'coin-boost-t1',
    name: 'AMULETO DE COBRE',
    description: '+25% MONEDAS EN 3 ENTREGAS',
    fullDescription: 'Talisman financiero introductorio emitido por el Banco para bonificar las primeras victorias.',
    type: 'BUFF',
    family: 'COINS',
    tier: 'COMUN',
    price: 200,
    icon: 'coin',
    accent: 'YELLOW',
    imageUrl: 'assets/monedasSINfondo.png',
    imageAlt: 'Amuleto de cobre',
    status: 'AVAILABLE',
    effect: 'x1.25 monedas'
  },
  {
    id: 'coin-boost-t2',
    name: 'IMAN DE MONEDAS',
    description: '+50% MONEDAS EN 5 ENTREGAS',
    fullDescription: 'Dispositivo magnetico que incrementa en un 50% el circulante cobrado en cada resolucion exitosa.',
    type: 'BUFF',
    family: 'COINS',
    tier: 'POCO COMUN',
    price: 500,
    icon: 'coin',
    accent: 'CYAN',
    imageUrl: 'assets/monedasSINfondo.png',
    imageAlt: 'Iman de monedas',
    status: 'AVAILABLE',
    effect: 'x1.5 monedas'
  },
  {
    id: 'coin-boost-t3',
    name: 'TALISMAN DEL TESORO',
    description: 'DUPLICA MONEDAS EN 8 ENTREGAS',
    fullDescription: 'Reliquia bancaria de alto rendimiento que duplica los pagos directos acreditados por el Banco.',
    type: 'BUFF',
    family: 'COINS',
    tier: 'RARO',
    price: 1000,
    icon: 'coin',
    accent: 'PINK',
    imageUrl: 'assets/monedasSINfondo.png',
    imageAlt: 'Talisman del tesoro',
    status: 'AVAILABLE',
    effect: 'x2 monedas'
  },
  {
    id: 'coin-boost-t4',
    name: 'COFRE DE LA ABUNDANCIA',
    description: 'X2.5 MONEDAS EN 12 ENTREGAS',
    fullDescription: 'Contrato fiduciario para estudiantes avanzados que garantiza retorno financiero extraordinario en 12 entregas exitosas.',
    type: 'BUFF',
    family: 'COINS',
    tier: 'EPICO',
    price: 2000,
    icon: 'coin',
    accent: 'YELLOW',
    imageUrl: 'assets/monedasSINfondo.png',
    imageAlt: 'Cofre de la abundancia',
    status: 'AVAILABLE',
    effect: 'x2.5 monedas'
  },
  {
    id: 'coin-boost-t5',
    name: 'TOQUE DORADO DE MIDAS',
    description: 'TRIPLICA MONEDAS EN 20 ENTREGAS',
    fullDescription: 'El multiplicador de riqueza supremo del Mercado. Triplica la recompensa de 20 entregas aprobadas.',
    type: 'BUFF',
    family: 'COINS',
    tier: 'LEGENDARIO',
    price: 4000,
    icon: 'coin',
    accent: 'YELLOW',
    imageUrl: 'assets/monedasSINfondo.png',
    imageAlt: 'Toque dorado de Midas',
    status: 'AVAILABLE',
    effect: 'x3 monedas'
  },
  {
    id: 'life-pack-01',
    name: 'VIDA EXTRA',
    description: 'RECUPERA UNA VIDA',
    fullDescription: 'Recupera una vida activa para seguir intentando desafios del curso sin cortar la racha.',
    type: 'LIFE',
    family: 'LIVES',
    tier: 'UNICA',
    price: 300,
    icon: 'heart',
    accent: 'PINK',
    imageUrl: 'assets/corazon.png',
    imageAlt: 'Vida extra',
    status: 'AVAILABLE',
    effect: '+1 vida activa'
  }
];
